### ISSUE TITLE
Error if existing annotations point to non-existent records

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/waveform-annotation#15]
I have loaded some new records and created new `RECORDS_VTVF` files; however, the existing database contains annotations for old records that are no longer listed in `RECORDS_VTVF`.

The following occurs upon loading `/waveform-annotation/waveforms/`:

```
Internal Server Error: /waveform-annotation/waveforms/django_plotly_dash/app/waveform_graph/initial/dpd-initial-args-eb30108d6d924f3081bcdd04a524b911/_dash-update-component
Traceback (most recent call last):
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django_plotly_dash/views.py", line 93, in _update
    resp = view_func()
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 560, in dispatch
    return self.dispatch_with_args(body, argMap=dict())
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 647, in dispatch_with_args
    res = self.callback_map[target_id]['callback'](*args, **argMap)
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/env3/lib64/python3.9/site-packages/dash/dash.py", line 985, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/waveform-django/./waveforms/dash_apps/finished_apps/waveform_vis.py", line 872, in get_record_event_options
    return_record, return_event = get_current_ann()
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/waveform-django/./waveforms/dash_apps/finished_apps/waveform_vis.py", line 487, in get_current_ann
    ann_indices = sorted([all_events.index(a) for a in completed_annotations])
  File "/var/www/vhosts/breadboard-lcp.mit.edu/Flask/waveform-annotation/waveform-django/./waveforms/dash_apps/finished_apps/waveform_vis.py", line 487, in <listcomp>
    ann_indices = sorted([all_events.index(a) for a in completed_annotations])
ValueError: 'ge1_1m' is not in list
```

**Comment by Lucas-Mc** [comment]
This should've been fixed in #20.
